### ISSUE TITLE
Add an option to disable homomorhic hashing in storage nodes

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1300]
There is a need to toggle calculation of objects' payload homomorphic hash in NeoFS environment. Disabling can speed up object formation.

### API
- [x]  add `bool homomorphic_hashing_disabled ` to [Container](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/container/types.proto#L15) message of the NeoFS API V2 protocol
- [x] create constant key to the corresponding value in network configuration stored in Morph chain (can it be defined in contract repo and imported to SDK from its packages?)
- [x] add function to modify container according to global network configuration
`func (*Container) ApplyNetworkConfig(netmap.NetworkConfig)`
- [x] add function to assert network configuration for the container
`func (Container) AssertNetworkConfig(netmap.NetworkConfig) bool`
- [x] add function to sync container with network state using API client
`func SyncContainerWithNetwork(context.Context, *container.Container, *Client) error`
P.S. to begin with, I propose leaving `Client.ContainerPut`  to accept prepared `Container` structure, and perform all preparation stages outside.

#### Container approval
- [x] make [checkPutContainer](https://github.com/nspcc-dev/neofs-node/blob/1fc9351f4feb83ba90fca247fd8ac77865caf5a2/pkg/innerring/processors/container/process_container.go#L65) method of Container processor to:
1. receive network config using Morph client
2. assert network configuration for the stored container using `AssertNetworkConfig`
3. return an error on false return

####  Data audit
- [x] make data audit [routine](https://github.com/nspcc-dev/neofs-node/blob/606dfa341437795b56a46bb6234b3a017cc5fff8/pkg/services/audit/auditor/por.go#L38) to not validate homomorphic hash of the objects if `homomorphic_hashing_disabled` flag is set in the container of the storage group under audit (maybe `Context` is the best place to store this info).

### Storage node
- [x] make [payloadSizeLimiter](https://github.com/nspcc-dev/neofs-node/blob/1fc9351f4feb83ba90fca247fd8ac77865caf5a2/pkg/services/object_manager/transformer/transformer.go#L131) to calculate homomorphic hash of the payload if `homomorphic_hashing_disabled` is set
- [x] make Object Put [service](https://github.com/nspcc-dev/neofs-node/blob/606dfa341437795b56a46bb6234b3a017cc5fff8/pkg/services/object/put/streamer.go#L91) to pass `homomorphic_hashing_disabled` to `payloadSizeLimiter` from the `Container` of the request context (as an optimization we can try to provide a quick access to the container for Object service e.g. from the `context.Context`)
- [x] do not validate homomorphic hash during object validation if `homomorphic_hashing_disabled` is set in the corresponding container (maybe this isn't checked at all)

### NeoFS CLI

- [x] make container [create](https://github.com/nspcc-dev/neofs-node/blob/606dfa341437795b56a46bb6234b3a017cc5fff8/cmd/neofs-cli/modules/container.go#L139) command to call `SyncContainerWithNetwork` for the container before storing it
- [x] make storagegroup [put](https://github.com/nspcc-dev/neofs-node/blob/606dfa341437795b56a46bb6234b3a017cc5fff8/cmd/neofs-cli/modules/storagegroup.go#L163) command to not calculate homomorphic hash field if flag is set.

**Comment by fyrchik** [comment]
What does this option do, exactly? For example, when I put an object via such node with a session token, it would be put without homomorphic hash?

**Comment by alexvanin** [comment]
There are two primary use cases of the tz-hash lib in NeoFS:
1. calculate homomorphic hashes at object.Put request (when receiving incomplete object),
2. use homomorphic properties during data audit in IR.

I think both should be disabled if we consider global network option.

**Comment by cthulhu-rider** [comment]
If network config, then static, right?

**Comment by realloc** [comment]
I'd suggest using both network settings and container attribute. When network setting is toggled, it affects the attribute set in container.

**Comment by carpawell** [comment]
@realloc, what do you mean by saying "affects the attribute set in container"?  Literally changing its value?

**Comment by realloc** [comment]
> @realloc, what do you mean by saying "affects the attribute set in container"? Literally changing its value?

Doesn't allow to create a container with the attribute conflicting current network settings. For example if there is network setting `DisableTZHash=True`, then all containers without `DisableTZHash=True` attribute considered invalid.

**Comment by alexvanin** [comment]
@realloc can you elaborate the concept of _invalid_ containers? As for now, we check container validity in Alphabet nodes during container creation. Therefore container will _always be valid_ after approval.

Does the scheme stays the same in your proposal? Or you consider having _invalid_ containers after creation (created before `DisableTZHash` setting toggle). If so, then describe how storage and inner ring nodes should behave with requests of _invalid_ containers.

**Comment by realloc** [comment]
The proposed scheme just adds a step at IR container validity check.

**Comment by cthulhu-rider** [comment]
> using both network settings and container attribute

Final solution.

- IR denies container if flag differs with network config
- SN processes container flag only

**Comment by cthulhu-rider** [comment]
Implemented in https://github.com/nspcc-dev/neofs-node/tree/feat/optional-homomorphic-hashing.
