### ISSUE TITLE
Storage Group validation

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1662]
- [x] https://github.com/nspcc-dev/neofs-api/issues/233
- [x] https://github.com/nspcc-dev/neofs-sdk-go/issues/310
- [x] https://github.com/nspcc-dev/neofs-node/issues/1661
- [x] https://github.com/nspcc-dev/neofs-node/issues/1660
- [x] https://github.com/nspcc-dev/neofs-node/issues/1659

**Comment by roman-khimov** [comment]
Obsolete, see https://github.com/nspcc-dev/neofs-node/issues/3442.
