### ISSUE TITLE
IR: Listen and process `Subnet.Put/Delete` notifications

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#973]
* Blocked by https://github.com/nspcc-dev/neofs-sdk-go/issues/79
* Related to https://github.com/nspcc-dev/neofs-contract/issues/122

## Summary
`Put` method of `Subnet` contract throws notifications about new subnetworks (carries IDs and binary information). Alphabet nodes should verify all infos and approve only valid ones. Approved subnets will be eventually  stored in `Subnet` contract.

## Task

- [x] Define format of `Put` notification event. Implement notification parser.
- [x] Create IR subnet processor and make it to listen for `Put` notifications from sidechain.
- [x] Verify the event data: it must have non-empty valid ID and owner ID.
- [x] Implement morph client's method to call `Put` method of `Subnet` contract.
- [x] Call `Put` method on notification event approval.

### UPD @cthulhu-rider 24.11.21
`Delete` notifications should be processed also.
