### ISSUE TITLE
IR: Listen and process `RemoveNode` notifications of `Subnet` contract

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#977]
Related to 
* nspcc-dev/neofs-contract#122
* nspcc-dev/neofs-node#974

## Summary

`RemoveNode` methods of `Subnet` contract throws notifications about nodes excluded from the subnet. Alphabetic nodes should respond to this by removing the subnet attribute from the node information as a candidate for a network map. If a node remains outside of any subnet, then it loses its candidacy.

## Task

- [ ] Define format of `RemoveNode` notification event. Implement notification parser.

- [ ] Make Netmap processor to listen for `RemoveNode` notifications from sidechain.

- [ ] If removed node is a netmap candidate then do same subnet-related steps as in nspcc-dev/neofs-node#974 but call `AddPeer` if node has been left the subnet (`UpdateState(StateOffline)` if the subnet was the only one).
