### ISSUE TITLE
Add administation module for subnetworks

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#979]
* Blocked by https://github.com/nspcc-dev/neofs-contract/issues/122

## Summary
`Subnet` contract of NeoFS sidechain provides the functionality to create, manage and remove NeoFS subnetworks. We need to provide convenient functionality which allows to do it from admin utility.

## Task

- [ ] Add `subnet` module (`cobra.Command`).
- [ ] Add `create` sub-command which creates new subnetwork using a private key. ID is generated randomly. It'd nice to provide same await approach as `neofs-cli container create`.
- [ ] Add `remove` sub-command which removes subnetwork by ID using a private key. It'd nice to provide same await approach as `neofs-cli container delete`.
- [ ] Provide access to methods for managing lists of keys (clients and nodes) with commands of the same name. Add/remove takes a list of keys. To manage client keys group ID should be provided or generated randomly.

**Comment by alexvanin** [comment]
Besides control of subnet contract, neofs-adm utility should deploy this contract at `init` and `update` stage for this release.
